"""remove_is_cross_department

Revision ID: 3c3176afb43c
Revises: a38f98b8c796
Create Date: 2026-06-14 11:15:14.367348
"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '3c3176afb43c'
down_revision: Union[str, None] = 'a38f98b8c796'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('mapping_report_entries', 'is_cross_department')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('mapping_report_entries', sa.Column('is_cross_department', sa.BOOLEAN(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
