"""init_schema

Revision ID: 40ba1d6c079f
Revises: 
Create Date: 2026-05-27 22:48:50.853556
"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '40ba1d6c079f'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('expertise_tags',
    sa.Column('canonical_label', sa.String(length=255), nullable=False),
    sa.Column('domain', sa.String(length=255), nullable=True),
    sa.Column('embedding', postgresql.ARRAY(sa.Float()), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('canonical_label', name='uq_expertise_canonical')
    )
    op.create_table('users',
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('ACADEMIC_STAFF', 'FACULTY_ADMINISTRATOR', name='user_role'), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'ACTIVE', 'REJECTED', 'SUSPENDED', name='account_status'), nullable=False),
    sa.Column('department', sa.String(length=255), nullable=True),
    sa.Column('is_dual_role', sa.Boolean(), nullable=False),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('first_login_completed', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email', name='uq_users_email')
    )
    op.create_table('academic_background',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('category', sa.Enum('ADMINISTRATIVE_ROLE', 'AWARD', 'EDUCATION', name='academic_background_category'), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('organization', sa.String(length=255), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('end_date IS NULL OR end_date >= start_date', name='ck_academic_background_chronology'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_academic_background_user_id'), 'academic_background', ['user_id'], unique=False)
    op.create_table('benchmark_runs',
    sa.Column('triggered_by', sa.UUID(), nullable=True),
    sa.Column('benchmark_type', sa.Enum('GLOBAL', 'PEER', name='benchmark_type'), nullable=False),
    sa.Column('source_payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('visualization_payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('narrative', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['triggered_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('course_grant_specs',
    sa.Column('created_by', sa.UUID(), nullable=False),
    sa.Column('spec_type', sa.Enum('COURSE', 'GRANT', name='specification_type'), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('raw_text', sa.Text(), nullable=False),
    sa.Column('source_filename', sa.String(length=255), nullable=True),
    sa.Column('embedding', postgresql.ARRAY(sa.Float()), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_course_grant_specs_created_by'), 'course_grant_specs', ['created_by'], unique=False)
    op.create_table('notification_log',
    sa.Column('recipient_user_id', sa.UUID(), nullable=True),
    sa.Column('recipient_email', sa.String(length=320), nullable=False),
    sa.Column('kind', sa.Enum('REGISTRATION_APPROVED', 'REGISTRATION_REJECTED', 'PASSWORD_RESET', name='notification_kind'), nullable=False),
    sa.Column('subject', sa.String(length=255), nullable=False),
    sa.Column('delivered', sa.Boolean(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('retry_count', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['recipient_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('orcid_profiles',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('orcid_id', sa.String(length=19), nullable=False),
    sa.Column('last_sync_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("orcid_id ~ '^[0-9]{4}-[0-9]{4}-[0-9]{4}-[0-9]{3}[0-9X]$'", name='ck_orcid_format'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('orcid_id', name='uq_orcid_id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('password_reset_tokens',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('token', sa.String(length=128), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('consumed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token', name='uq_password_reset_token')
    )
    op.create_index(op.f('ix_password_reset_tokens_user_id'), 'password_reset_tokens', ['user_id'], unique=False)
    op.create_table('portfolios',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('portfolio_type', sa.Enum('FACULTY_MANAGER', 'HEAD_OF_DEPARTMENT', 'DEPUTY_DEAN_RESEARCH', 'DEPUTY_DEAN_UGPG', name='portfolio_type'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'portfolio_type', name='uq_user_portfolio')
    )
    op.create_index(op.f('ix_portfolios_user_id'), 'portfolios', ['user_id'], unique=False)
    op.create_table('publications',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('doi', sa.String(length=255), nullable=False),
    sa.Column('title', sa.Text(), nullable=True),
    sa.Column('venue', sa.String(length=512), nullable=True),
    sa.Column('publication_year', sa.Integer(), nullable=True),
    sa.Column('openalex_id', sa.String(length=64), nullable=True),
    sa.Column('abstract_missing', sa.Boolean(), nullable=False),
    sa.Column('embedding', postgresql.ARRAY(sa.Float()), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'doi', name='uq_publication_user_doi')
    )
    op.create_index(op.f('ix_publications_user_id'), 'publications', ['user_id'], unique=False)
    op.create_table('sync_jobs',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('trigger', sa.Enum('FIRST_LOGIN', 'MANUAL', 'QUARTERLY', name='sync_trigger'), nullable=False),
    sa.Column('status', sa.Enum('QUEUED', 'RUNNING', 'SUCCEEDED', 'FAILED', 'NO_NEW_DATA', name='sync_job_status'), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('publications_added', sa.Integer(), nullable=False),
    sa.Column('tags_added', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sync_jobs_user_id'), 'sync_jobs', ['user_id'], unique=False)
    op.create_table('user_expertise_tags',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('tag_id', sa.UUID(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('validated', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['tag_id'], ['expertise_tags.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'tag_id', name='uq_user_expertise_pair')
    )
    op.create_index(op.f('ix_user_expertise_tags_tag_id'), 'user_expertise_tags', ['tag_id'], unique=False)
    op.create_index(op.f('ix_user_expertise_tags_user_id'), 'user_expertise_tags', ['user_id'], unique=False)
    op.create_table('benchmark_white_spaces',
    sa.Column('run_id', sa.UUID(), nullable=False),
    sa.Column('domain_label', sa.String(length=255), nullable=False),
    sa.Column('displacement_score', sa.Float(), nullable=False),
    sa.Column('recommendation', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['benchmark_runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_benchmark_white_spaces_run_id'), 'benchmark_white_spaces', ['run_id'], unique=False)
    op.create_table('mapping_reports',
    sa.Column('spec_id', sa.UUID(), nullable=False),
    sa.Column('generated_by', sa.UUID(), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['generated_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['spec_id'], ['course_grant_specs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mapping_reports_spec_id'), 'mapping_reports', ['spec_id'], unique=False)
    op.create_table('publication_abstracts',
    sa.Column('publication_id', sa.UUID(), nullable=False),
    sa.Column('abstract_text', sa.Text(), nullable=False),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('supplemented_by_user_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['publication_id'], ['publications.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['supplemented_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('publication_id')
    )
    op.create_table('mapping_report_entries',
    sa.Column('report_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('rank', sa.Integer(), nullable=False),
    sa.Column('cosine_score', sa.Float(), nullable=False),
    sa.Column('spreading_score', sa.Float(), nullable=False),
    sa.Column('combined_score', sa.Float(), nullable=False),
    sa.Column('is_cross_department', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['report_id'], ['mapping_reports.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('report_id', 'user_id', name='uq_mapping_report_user')
    )
    op.create_index(op.f('ix_mapping_report_entries_report_id'), 'mapping_report_entries', ['report_id'], unique=False)
    op.create_index(op.f('ix_mapping_report_entries_user_id'), 'mapping_report_entries', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_mapping_report_entries_user_id'), table_name='mapping_report_entries')
    op.drop_index(op.f('ix_mapping_report_entries_report_id'), table_name='mapping_report_entries')
    op.drop_table('mapping_report_entries')
    op.drop_table('publication_abstracts')
    op.drop_index(op.f('ix_mapping_reports_spec_id'), table_name='mapping_reports')
    op.drop_table('mapping_reports')
    op.drop_index(op.f('ix_benchmark_white_spaces_run_id'), table_name='benchmark_white_spaces')
    op.drop_table('benchmark_white_spaces')
    op.drop_index(op.f('ix_user_expertise_tags_user_id'), table_name='user_expertise_tags')
    op.drop_index(op.f('ix_user_expertise_tags_tag_id'), table_name='user_expertise_tags')
    op.drop_table('user_expertise_tags')
    op.drop_index(op.f('ix_sync_jobs_user_id'), table_name='sync_jobs')
    op.drop_table('sync_jobs')
    op.drop_index(op.f('ix_publications_user_id'), table_name='publications')
    op.drop_table('publications')
    op.drop_index(op.f('ix_portfolios_user_id'), table_name='portfolios')
    op.drop_table('portfolios')
    op.drop_index(op.f('ix_password_reset_tokens_user_id'), table_name='password_reset_tokens')
    op.drop_table('password_reset_tokens')
    op.drop_table('orcid_profiles')
    op.drop_table('notification_log')
    op.drop_index(op.f('ix_course_grant_specs_created_by'), table_name='course_grant_specs')
    op.drop_table('course_grant_specs')
    op.drop_table('benchmark_runs')
    op.drop_index(op.f('ix_academic_background_user_id'), table_name='academic_background')
    op.drop_table('academic_background')
    op.drop_table('users')
    op.drop_table('expertise_tags')
    # ### end Alembic commands ###
