"""make_start_date_optional

Revision ID: a38f98b8c796
Revises: 247266f538ba
Create Date: 2026-06-07 18:30:58.549046
"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'a38f98b8c796'
down_revision: Union[str, None] = '247266f538ba'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('academic_background', 'start_date',
               existing_type=sa.DATE(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('academic_background', 'start_date',
               existing_type=sa.DATE(),
               nullable=False)
    # ### end Alembic commands ###
